USE [master]
GO

/****** Object:  Database [TodoDBNetCore]    Script Date: 8/16/2018 11:16:39 AM ******/
CREATE DATABASE [TodoDBNetCore]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'TodoDBNetCore', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\TodoDBNetCore.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'TodoDBNetCore_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\TodoDBNetCore_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [TodoDBNetCore] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [TodoDBNetCore].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [TodoDBNetCore] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [TodoDBNetCore] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [TodoDBNetCore] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [TodoDBNetCore] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [TodoDBNetCore] SET ARITHABORT OFF 
GO

ALTER DATABASE [TodoDBNetCore] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [TodoDBNetCore] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [TodoDBNetCore] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [TodoDBNetCore] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [TodoDBNetCore] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [TodoDBNetCore] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [TodoDBNetCore] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [TodoDBNetCore] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [TodoDBNetCore] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [TodoDBNetCore] SET  DISABLE_BROKER 
GO

ALTER DATABASE [TodoDBNetCore] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [TodoDBNetCore] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [TodoDBNetCore] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [TodoDBNetCore] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [TodoDBNetCore] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [TodoDBNetCore] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [TodoDBNetCore] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [TodoDBNetCore] SET RECOVERY FULL 
GO

ALTER DATABASE [TodoDBNetCore] SET  MULTI_USER 
GO

ALTER DATABASE [TodoDBNetCore] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [TodoDBNetCore] SET DB_CHAINING OFF 
GO

ALTER DATABASE [TodoDBNetCore] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [TodoDBNetCore] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [TodoDBNetCore] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [TodoDBNetCore] SET  READ_WRITE 
GO



USE [TodoDBNetCore]
GO

/****** Object:  Table [dbo].[TodoItem]    Script Date: 8/16/2018 11:17:10 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[TodoItem](
	[Id] [int] NOT NULL,
	[Name] [nvarchar](50) NOT NULL,
	[IsComplete] [bit] NULL,
 CONSTRAINT [PK_TodoItem] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
